export const DATA = {
  name: "Santiago",
  title: "Fullstack Developer",
  tagline: "Enfocado en sistemas reales, SaaS y automatización.",
  email: "santiago.aguilar.dev@gmail.com",
  github: "https://github.com/santiago-dev",
  cv: "https://raw.githubusercontent.com/Santiag0Aguilar/Mi-portafolio/main/CV_Santiago_Aguilar.pdf",
  about: [
    "Desarrollador Fullstack Junior en proceso constante de mejora.",
    "",
    "Me interesa entender cómo funcionan las cosas por dentro,",
    "especialmente en el backend, y construir productos que sean",
    "claros, funcionales y fáciles de usar.",
    "",
    "Busco mi primera oportunidad profesional para aportar valor,",
    "aprender rápido y crecer dentro de la industria.",
    "",
    "Actualmente abierto a oportunidades full-time.",
  ],

  skills: {
    Frontend: [
      { name: "JavaScript", cls: "js" },
      { name: "React", cls: "react" },
      { name: "HTML5", cls: "html" },
      { name: "CSS3", cls: "css" },
      { name: "Sass", cls: "sass" },
    ],
    Backend: [
      { name: "Node.js", cls: "node" },
      { name: "Express", cls: "expr" },
      { name: "Java(Basico)", cls: "java" },
    ],
    Databases: [
      { name: "MySQL", cls: "mysql" },
      { name: "PostgreSQL", cls: "pg" },
    ],
    Tools: [
      { name: "Git", cls: "git" },
      { name: "REST APIs", cls: "api" },
    ],
  },
  projects: [
    {
      id: 1,
      name: "InnBeta — SaaS de menús digitales",
      stack: "React · Node.js · Express · Prisma · PostgreSQL · JWT",
      status: "🟢 Live",
      year: "2026",
      description: [
        "Plataforma SaaS que sincroniza catálogos de negocios vía API de Loyverse y genera menús digitales",
        "públicos con dashboard administrativo.",
        " ",
        "• Arquitectura REST desacoplada frontend/backend",
        "• Sincronización optimizada: N queries → bulk upserts",
        "• Mapeo en memoria para escritura eficiente en PostgreSQL",
        "• Middleware de seguridad: rate limit, sanitización, Helmet",
        "• Autenticación JWT y arquitectura multi-tenant",
        "• Tracking de eventos analíticos para dashboard futuro",
      ],
      demo: "https://app-menudigital.netlify.app/",
      repo: "https://github.com/Santiag0Aguilar/App-MenuDigital",
    },
    {
      id: 2,
      name: "Calculadora interactiva — Frontend Mentor",
      stack: "HTML5 · SASS (SCSS) · JavaScript · CSS Grid · Flexbox · Gulp",
      status: "🟢 Live",
      year: "2025",
      description: [
        "Aplicación web interactiva enfocada en fundamentos sólidos de frontend y diseño responsivo.",
        " ",
        "• Layout responsive usando CSS Grid + Flexbox",
        "• Sistema de temas dinámico controlado con JavaScript",
        "• Manejo de eventos DOM para operaciones matemáticas",
        "• Automatización de estilos con SASS + Gulp",
        "• UI interactiva con efectos :hover y feedback visual",
      ],
      demo: "https://santiag0aguilar.github.io/CalculadoraFrontEndMentor/",
      repo: "https://github.com/Santiag0Aguilar/CalculadoraFrontEndMentor",
    },
  ],
};
export const COMMANDS = [
  "help",
  "about",
  "skills",
  "projects",
  "project",
  "contact",
  "cv",
  "whoami",
  "date",
  "clear",
  "exit",
  "SELECT * FROM projects;",
  "SHOW SKILLS;",
  "SHOW PROJECTS;",
];
export const COMMAND_HINTS = {
  help: "List all available commands",
  about: "About me — background & focus",
  skills: "My technical skill set",
  projects: "All projects overview",
  project: "project <id> — detailed project info",
  contact: "Contact info & social links",
  cv: "Download / view my resume",
  whoami: "Quick profile summary",
  date: "Current date & time",
  clear: "Clear the terminal",
  exit: "End session",
};
